// Generated by https://quicktype.io

export interface GymListResponse {
    content:       Gym[];
    size:          number;
    totalElements: number;
    pageNumber:    number;
    first:         boolean;
    last:          boolean;
    
}

export interface Gym {
    id:                string;
    name:              string;
    avgBelt:           string;
    latitude:          number;
    altitude:          number;
    numberTournaments: number;
}
