// Generated by https://quicktype.io

export interface GymPercentageTournamentResponse {
    totalTournaments: number;
    gyms:             Gym[];
}

export interface Gym {
    gymName:    string;
    numberOfTournaments: number;
}
