// Generated by https://quicktype.io

export interface LoginResponse {
    id:            string;
    username:      string;
    userBeltColor: string;
    rol:           string;
    token:         string;
}
