// Generated by https://quicktype.io

export interface TournamentListResponse {
    content:       Tournament[];
    size:          number;
    totalElements: number;
    pageNumber:    number;
    first:         boolean;
    last:          boolean;
}

export interface Tournament {
    id:           string;
    title:        string;
    date:         Date;
    cost:         number;
    participants: number;
    applied:      number;
    higherBelt:   string;
    prize:        number;
    author:       string;
    minWeight:    number;
    maxWeight:    number;
    city:         string;
}
