// Generated by https://quicktype.io

export interface UserListResponse {
    content:       User[];
    size:          number;
    totalElements: number;
    pageNumber:    number;
    first:         boolean;
    last:          boolean;
}

export interface User {
    id:       string;
    name:     string;
    surname:  string;
    username: string;
    belt:     string;
    age:      number;
    weight:   number;
    height:   number;
    sex:      number;
    email:    string;
}

