// Generated by https://quicktype.io

export interface UserBestPoster {
    name:          string;
    surname:       string;
    username:      string;
    belt:          string;
    postPublished: number;
}
